### ISSUE TITLE
Create independent scrollbars for sidebar and main area

### ISSUE THREAD

**Issue by MarcSkovMadsen** [MarcSkovMadsen/awesome-panel#4]
#### My pain

Normally the sidebar should not scroll when we scroll the main area for ease of use. But the sidebar still needs to be able to scroll as for some use cases there might be a longer list of menu items or other widgets.

I also wan't to disable horizontal scrolling as I think this is annoying. Instead I should make sure in the layout of things that they dont overflow horizontally.

#### Solution

Add independent scrollbars to sidebar and nav area.

#### Additional context

Something along the lines of the below should do the trick when added to https://github.com/MarcSkovMadsen/awesome-panel/blob/master/package/awesome_panel/express/templates/bootstrap_dashboard/bootstrap_dashboard.css

```css
body {
    overflow-x: hidden;
    overflow-y: hidden;
  }
nav {
    overflow-y: scroll;
  }
main {
    overflow-y: scroll;
  }
````
